name: Check New Commit

on:
  push:
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check for new commit
      run: |
        git fetch origin main
        if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
          echo "New commit detected!"
        else
          echo "No new commits."
          exit 1
        fi
